package io.tatkalrush.application.ports;

import io.tatkalrush.domain.pricing.RefundReason;
import java.time.Instant;
import java.util.List;
import java.util.Optional;

/** Persistence for payments, refunds and the ledger (§10.3). */
public interface PaymentRepository {

    /** Mirrors {@code payments.status}'s CHECK constraint. */
    enum PaymentStatus {
        INITIATED,
        SUCCESS,
        FAILED,
        REFUNDED
    }

    /** Mirrors {@code ledger_entries.entry_type}'s CHECK constraint. */
    enum LedgerEntryType {
        CHARGE,
        REFUND
    }

    record PaymentRecord(
            long id,
            long bookingId,
            String paymentReference,
            long amountPaise,
            PaymentStatus status,
            Instant initiatedAt,
            Optional<Instant> settledAt) {}

    /**
     * The captured payment for a booking, if money has actually moved.
     *
     * <p>Returns empty for a payment still {@code INITIATED}. Refund logic asks
     * this question rather than "is there a payment row", because a payment row
     * exists from the moment we intended to charge — refunding against intent
     * would send money we never took.
     */
    Optional<PaymentRecord> findCapturedFor(long bookingId);

    /** The payment for a booking whatever its status. */
    Optional<PaymentRecord> findFor(long bookingId);

    Optional<PaymentRecord> findByReference(String paymentReference);

    /**
     * @param paymentReference generated by us and used as the PSP's idempotency
     *     key. {@code payments.psp_payment_id} is {@code UNIQUE}, so a replayed
     *     initiation blocks on the index rather than creating a second charge.
     */
    record NewPayment(long bookingId, String paymentReference, long amountPaise) {}

    /** Writes the intent to charge, before the gateway is called. */
    long create(NewPayment payment);

    /**
     * Compare-and-set from {@code INITIATED} to a terminal status.
     *
     * <p>This is the layer that makes settlement exactly-once <b>across routes</b>.
     * FR-22's {@code (payment_id, event_type)} unique key stops the same webhook
     * being applied twice; it cannot stop a webhook and FR-23's reconciliation poll
     * from both settling, because the poll carries no event and so shares no key
     * with the webhook. The status transition is the one thing both routes must
     * pass through.
     *
     * @return whether this caller performed the transition. {@code false} means it
     *     was already settled, which is a no-op and not an error.
     */
    boolean settle(String paymentReference, PaymentStatus terminal, Instant settledAt);

    /**
     * Records a webhook delivery, insert-first (FR-22).
     *
     * <p>{@code INSERT ... ON CONFLICT DO NOTHING} on
     * {@code (psp_payment_id, event_type)}. Insert-first rather than check-then-act
     * for the reason DD-009 gives: two concurrent redeliveries both see an empty
     * table and both proceed. FR-55 double-delivers 5% of webhooks on purpose, so
     * this is a designed-for case, not a rare one.
     *
     * <p>{@code event_type} is one of our own enum names, never the PSP's string.
     * A provider that renames {@code payment.succeeded} to
     * {@code payment_succeeded} would otherwise open a fresh dedup bucket and the
     * same event would settle twice.
     *
     * @return {@code false} if this exact event was already recorded
     */
    boolean recordEvent(String paymentReference, String eventType, String payload);

    /** A booking stuck mid-payment, with whatever payment row it has. */
    record PendingSettlement(long bookingId, PaymentRecord payment) {}

    /**
     * FR-23: bookings in {@code PAYMENT_PENDING} whose payment was initiated
     * before {@code cutoff}.
     *
     * <p>Selected by <b>state</b>, never by the absence of an event row. A crash
     * between settling the payment and confirming the booking leaves the
     * {@code PAYMENT_SUCCEEDED} event already recorded, so an event-driven sweep
     * would conclude "already handled" and skip it — stranding a captured payment
     * on a booking that never advanced, which is exactly the INV-3 violation FR-23
     * exists to prevent.
     */
    List<PendingSettlement> findPendingSettlements(Instant cutoff, int limit);

    /**
     * Records the <b>intention</b> to refund, before the PSP is called.
     *
     * <p>Writes a {@code refunds} row with {@code status = 'PENDING'} and returns
     * its id. If the process dies during the gateway call, this row is the
     * evidence a retry needs; the alternative ordering — call first, record after
     * — loses the money silently and INV-3 has no way to notice.
     *
     * @return the new refund's id
     */
    long openRefund(long bookingId, long paymentId, long amountPaise, RefundReason reason);

    /**
     * Marks a refund {@code COMPLETED}, sets the payment to {@code REFUNDED} and
     * writes the {@code REFUND} ledger entry — as one transaction's worth of work.
     */
    void completeRefund(long refundId, long paymentId, long bookingId, long amountPaise);

    /**
     * Marks a refund {@code FAILED}.
     *
     * <p>The payment deliberately stays {@code SUCCESS}: money is still with the
     * PSP, and recording it as {@code REFUNDED} would make the ledger claim a
     * movement that did not happen.
     */
    void failRefund(long refundId);

    void recordLedgerEntry(long bookingId, LedgerEntryType type, long amountPaise);
}
