package io.tatkalrush.application.ports;

/**
 * Source of payment references (§12).
 *
 * <p>The reference is generated by <b>us</b> and handed to the PSP as its
 * idempotency key, which is what allows the intent row to be written before the
 * charge call. Generated by the PSP instead, the ordering would have to invert —
 * call first, record after — and a crash in between would leave money captured
 * with nothing in our database pointing at it. INV-3 would report an orphan with
 * no way to find its owner.
 *
 * <p>A port rather than an inline {@code UUID.randomUUID()} so tests can pin the
 * value. Nothing here needs unguessability: {@code payments.psp_payment_id} is
 * {@code UNIQUE}, so the guarantee that matters is collision-freedom, and the
 * database enforces it rather than trusting the generator.
 */
public interface PaymentReferences {

    String next();
}
