package io.tatkalrush.application.ports;

/**
 * The payment service provider, as the application sees it (§12).
 *
 * <p><b>Never called inside a database transaction.</b> FR-53 gives the simulator
 * a p99 of six seconds; a pooled connection held across that call means twenty
 * connections serve about three requests a second. Every use case that touches
 * this port commits before calling it and opens a new transaction afterwards, and
 * that shape is a consequence of this sentence rather than a style preference.
 *
 * <h2>Three outcomes, not two</h2>
 *
 * <p>Both operations distinguish {@code Rejected} from {@code Unreachable}, and
 * the distinction is the single most commonly-missed thing in payment
 * integrations:
 *
 * <ul>
 *   <li>{@code Rejected} — the PSP answered, and the answer was no. Nothing was
 *       captured. Safe to mark failed.
 *   <li>{@code Unreachable} — <b>we do not know.</b> The request may have been
 *       processed, the response lost. Treating this as failure risks marking a
 *       captured payment as failed, which orphans real money and violates INV-3.
 * </ul>
 *
 * <p>The only correct response to {@code Unreachable} is to leave the payment
 * where it is and let FR-23's reconciliation poll resolve it. That requirement is
 * not defensive engineering — it is the reason FR-23 exists.
 */
public interface PaymentGateway {

    /**
     * A charge request.
     *
     * @param paymentReference generated by <em>us</em>, not the PSP, and used as
     *     the PSP's idempotency key. Client-generated so the intent can be
     *     written durably <em>before</em> the call: a crash mid-charge then
     *     leaves a recoverable row rather than money with no record of it.
     */
    record ChargeRequest(String paymentReference, long bookingId, long amountPaise) {}

    sealed interface ChargeOutcome {
        /** The PSP accepted the charge. Settlement is asynchronous (FR-53). */
        record Accepted() implements ChargeOutcome {}

        /** The PSP answered no. Nothing captured. */
        record Rejected(String reason) implements ChargeOutcome {}

        /** No answer. The charge may or may not have happened (see class doc). */
        record Unreachable(String detail) implements ChargeOutcome {}
    }

    ChargeOutcome charge(ChargeRequest request);

    /**
     * A refund request (FR-57).
     *
     * @param reason carried through for the PSP's own records; the authoritative
     *     classification lives in {@code refunds.reason} on our side
     */
    record RefundRequest(String paymentReference, long amountPaise, String reason) {}

    sealed interface RefundOutcome {
        record Accepted() implements RefundOutcome {}

        record Rejected(String reason) implements RefundOutcome {}

        record Unreachable(String detail) implements RefundOutcome {}
    }

    RefundOutcome refund(RefundRequest request);

    /** What the PSP believes about a payment (FR-23's poll). */
    enum RemoteStatus {
        INITIATED,
        SUCCESS,
        FAILED,

        /**
         * The PSP has never heard of this reference.
         *
         * <p>Reached when we wrote the intent row and then failed before the
         * charge call landed. Distinct from {@link #FAILED}, which means the PSP
         * tried and declined — one is our crash, the other is their decision, and
         * only the first is safe to abandon without any refund consideration.
         */
        UNKNOWN
    }

    RemoteStatus poll(String paymentReference);
}
